<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OPCUA_Types" nsURI="http://opcfoundation.org/UA" nsPrefix="OPCUA_Types">
  <eAnnotations source="http://www.eclipse.org/uml2/2.0.0/UML">
    <details key="originalName" value="OPC-UA_Types"/>
  </eAnnotations>
  <eSubpackages name="References" nsURI="http:///OPCUA_Types/References.ecore" nsPrefix="OPCUA_Types.References">
    <eClassifiers xsi:type="ecore:EClass" name="References"/>
    <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
    <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
    <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
    <eClassifiers xsi:type="ecore:EClass" name="Description"/>
    <eSubpackages name="HierachicalReferences" nsURI="http:///OPCUA_Types/References/HierachicalReferences.ecore"
        nsPrefix="OPCUA_Types.References.HierachicalReferences">
      <eClassifiers xsi:type="ecore:EClass" name="HierachicalReferences" eSuperTypes="#//References/References">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
            eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
      <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
      <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
      <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
      <eSubpackages name="HasEventSource" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasEventSource.ecore"
          nsPrefix="OPCUA_Types.References.HierachicalReferences.HasEventSource">
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasEventSource" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="Organizes" nsURI="http:///OPCUA_Types/References/HierachicalReferences/Organizes.ecore"
          nsPrefix="OPCUA_Types.References.HierachicalReferences.Organizes">
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="Organizes" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="DataSetToWriter" nsURI="http:///OPCUA_Types/References/HierachicalReferences/DataSetToWriter.ecore"
          nsPrefix="OPCUA_Types.References.HierachicalReferences.DataSetToWriter">
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DataSetToWriter" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasChild" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild.ecore"
          nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasChild" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
        <eSubpackages name="HasSubtype" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/HasSubtype.ecore"
            nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.HasSubtype">
          <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
          <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
          <eClassifiers xsi:type="ecore:EClass" name="HasSubtype" eSuperTypes="#//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HierachicalReferences #//References/References">
            <eStructuralFeatures xsi:type="ecore:EReference" name="base_Generalization"
                ordered="false" eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Generalization"/>
          </eClassifiers>
        </eSubpackages>
        <eSubpackages name="Aggregates" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates.ecore"
            nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates">
          <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
          <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
          <eClassifiers xsi:type="ecore:EClass" name="Aggregates" eSuperTypes="#//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
          <eSubpackages name="HasProperty" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasProperty.ecore"
              nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasProperty">
            <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
            <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
            <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
            <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
            <eClassifiers xsi:type="ecore:EClass" name="HasProperty" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
          </eSubpackages>
          <eSubpackages name="HasComponent" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent.ecore"
              nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent">
            <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
            <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
            <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
            <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
            <eClassifiers xsi:type="ecore:EClass" name="HasComponent" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            <eSubpackages name="HasOrderedComponent" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasOrderedComponent.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasOrderedComponent">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasOrderedComponent" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            </eSubpackages>
            <eSubpackages name="HasWriterGroup" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasWriterGroup.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasWriterGroup">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasWriterGroup" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            </eSubpackages>
            <eSubpackages name="HasDataSetReader" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasDataSetReader.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasDataSetReader">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasDataSetReader" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            </eSubpackages>
            <eSubpackages name="HasPubSubConnection" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasPubSubConnection.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasPubSubConnection">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasPubSubConnection" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            </eSubpackages>
            <eSubpackages name="HasDataSetWriter" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasDataSetWriter.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasDataSetWriter">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasDataSetWriter" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            </eSubpackages>
            <eSubpackages name="HasReaderGroup" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasReaderGroup.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasReaderGroup">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasReaderGroup" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            </eSubpackages>
            <eSubpackages name="HasArgumentDescription" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasArgumentDescription.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasArgumentDescription">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasArgumentDescription"
                  eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
              <eSubpackages name="HasOptionalInputArgumentDescription" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasArgumentDescription/HasOptionalInputArgumentDescription.ecore"
                  nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasArgumentDescription.HasOptionalInputArgumentDescription">
                <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
                <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
                <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
                <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
                <eClassifiers xsi:type="ecore:EClass" name="HasOptionalInputArgumentDescription"
                    eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasArgumentDescription/HasArgumentDescription #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
              </eSubpackages>
            </eSubpackages>
            <eSubpackages name="HasGuard" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasGuard.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasGuard">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasGuard" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            </eSubpackages>
            <eSubpackages name="HasAddIn" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasAddIn.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasAddIn">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasAddIn" eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            </eSubpackages>
            <eSubpackages name="HasAlarmSuppressionGroup" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasAlarmSuppressionGroup.ecore"
                nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasComponent.HasAlarmSuppressionGroup">
              <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
              <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
              <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
              <eClassifiers xsi:type="ecore:EClass" name="HasAlarmSuppressionGroup"
                  eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HasChild/Aggregates/HasComponent/HasComponent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
            </eSubpackages>
          </eSubpackages>
          <eSubpackages name="HasHistoricalConfiguration" nsURI="http:///OPCUA_Types/References/HierachicalReferences/HasChild/Aggregates/HasHistoricalConfiguration.ecore"
              nsPrefix="OPCUA_Types.References.HierachicalReferences.HasChild.Aggregates.HasHistoricalConfiguration">
            <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
            <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
            <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
            <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
            <eClassifiers xsi:type="ecore:EClass" name="HasHistoricalConfiguration"
                eSuperTypes="#//References/HierachicalReferences/HasChild/Aggregates/Aggregates #//References/HierachicalReferences/HasChild/HasChild #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
          </eSubpackages>
        </eSubpackages>
      </eSubpackages>
    </eSubpackages>
    <eSubpackages name="NonHierachicalReferences" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences.ecore"
        nsPrefix="OPCUA_Types.References.NonHierachicalReferences">
      <eClassifiers xsi:type="ecore:EClass" name="NonHierachicalReferences" eSuperTypes="#//References/References">
        <eStructuralFeatures xsi:type="ecore:EReference" name="base_Association" ordered="false"
            eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Association"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
      <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
      <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
      <eSubpackages name="HasModellingRule" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasModellingRule.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasModellingRule">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasModellingRule" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasEncoding" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasEncoding.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasEncoding">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasEncoding" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasDescription" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasDescription.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasDescription">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasDescription" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="FromState" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/FromState.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.FromState">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="FromState" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="GeneratesEvent" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/GeneratesEvent.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.GeneratesEvent">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="GeneratesEvent" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
        <eSubpackages name="AlwaysGeneratesEvent" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/GeneratesEvent/AlwaysGeneratesEvent.ecore"
            nsPrefix="OPCUA_Types.References.NonHierachicalReferences.GeneratesEvent.AlwaysGeneratesEvent">
          <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
          <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
          <eClassifiers xsi:type="ecore:EClass" name="AlwaysGeneratesEvent" eSuperTypes="#//References/NonHierachicalReferences/GeneratesEvent/GeneratesEvent #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
        </eSubpackages>
      </eSubpackages>
      <eSubpackages name="ToState" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/ToState.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.ToState">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="ToState" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasTypeDefinition" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasTypeDefinition.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasTypeDefinition">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasTypeDefinition" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="AliasFor" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/AliasFor.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.AliasFor">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="AliasFor" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasFalseSubState" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasFalseSubState.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasFalseSubState">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasFalseSubState" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasCause" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasCause.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasCause">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasCause" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasDictionaryEntry" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasDictionaryEntry.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasDictionaryEntry">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasDictionaryEntry" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasInterface" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasInterface.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasInterface">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasInterface" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasTrueSubState" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasTrueSubState.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasTrueSubState">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasTrueSubState" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasSubStateMachine" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasSubStateMachine.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasSubStateMachine">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasSubStateMachine" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
      <eSubpackages name="HasEffect" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasEffect.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasEffect">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasEffect" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
        <eSubpackages name="HasEffectDisable" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasEffect/HasEffectDisable.ecore"
            nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasEffect.HasEffectDisable">
          <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
          <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
          <eClassifiers xsi:type="ecore:EClass" name="HasEffectDisable" eSuperTypes="#//References/NonHierachicalReferences/HasEffect/HasEffect #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
        </eSubpackages>
        <eSubpackages name="HasEffectEnable" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasEffect/HasEffectEnable.ecore"
            nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasEffect.HasEffectEnable">
          <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
          <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
          <eClassifiers xsi:type="ecore:EClass" name="HasEffectEnable" eSuperTypes="#//References/NonHierachicalReferences/HasEffect/HasEffect #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
        </eSubpackages>
        <eSubpackages name="HasEffectUnsuppressed" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasEffect/HasEffectUnsuppressed.ecore"
            nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasEffect.HasEffectUnsuppressed">
          <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
          <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
          <eClassifiers xsi:type="ecore:EClass" name="HasEffectUnsuppressed" eSuperTypes="#//References/NonHierachicalReferences/HasEffect/HasEffect #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
        </eSubpackages>
        <eSubpackages name="HasEffectSuppressed" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasEffect/HasEffectSuppressed.ecore"
            nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasEffect.HasEffectSuppressed">
          <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
          <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
          <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
          <eClassifiers xsi:type="ecore:EClass" name="HasEffectSuppressed" eSuperTypes="#//References/NonHierachicalReferences/HasEffect/HasEffect #//References/HierachicalReferences/HierachicalReferences #//References/References"/>
        </eSubpackages>
      </eSubpackages>
      <eSubpackages name="HasCondition" nsURI="http:///OPCUA_Types/References/NonHierachicalReferences/HasCondition.ecore"
          nsPrefix="OPCUA_Types.References.NonHierachicalReferences.HasCondition">
        <eClassifiers xsi:type="ecore:EClass" name="InverseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="BrowseName"/>
        <eClassifiers xsi:type="ecore:EClass" name="DisplayName"/>
        <eClassifiers xsi:type="ecore:EClass" name="NodeId"/>
        <eClassifiers xsi:type="ecore:EClass" name="HasCondition" eSuperTypes="#//References/HierachicalReferences/HierachicalReferences #//References/References"/>
      </eSubpackages>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="ObjectTypes" nsURI="http:///OPCUA_Types/ObjectTypes.ecore" nsPrefix="OPCUA_Types.ObjectTypes">
    <eClassifiers xsi:type="ecore:EClass" name="BaseObjectType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Class" ordered="false"
          eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Class"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="VariableTypes" nsURI="http:///OPCUA_Types/VariableTypes.ecore"
      nsPrefix="OPCUA_Types.VariableTypes">
    <eClassifiers xsi:type="ecore:EClass" name="BaseVariableType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_Variable" ordered="false"
          eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//Variable"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="DataTypes" nsURI="http:///OPCUA_Types/DataTypes.ecore" nsPrefix="OPCUA_Types.DataTypes">
    <eClassifiers xsi:type="ecore:EClass" name="BaseDataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="base_DataType" ordered="false"
          eType="ecore:EClass ../../org.eclipse.uml2.uml/model/UML.ecore#//DataType"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
