//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AggregateFilterResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AggregateFilterResult">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}MonitoringFilterResult">
 *       &lt;sequence>
 *         &lt;element name="RevisedStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="RevisedProcessingInterval" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="RevisedAggregateConfiguration" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}AggregateConfiguration" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AggregateFilterResult", propOrder = {
    "revisedStartTime",
    "revisedProcessingInterval",
    "revisedAggregateConfiguration"
})
public class AggregateFilterResult
    extends MonitoringFilterResult
{

    @XmlElement(name = "RevisedStartTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar revisedStartTime;
    @XmlElement(name = "RevisedProcessingInterval")
    protected Double revisedProcessingInterval;
    @XmlElementRef(name = "RevisedAggregateConfiguration", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<AggregateConfiguration> revisedAggregateConfiguration;

    /**
     * Gets the value of the revisedStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRevisedStartTime() {
        return revisedStartTime;
    }

    /**
     * Sets the value of the revisedStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRevisedStartTime(XMLGregorianCalendar value) {
        this.revisedStartTime = value;
    }

    /**
     * Gets the value of the revisedProcessingInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRevisedProcessingInterval() {
        return revisedProcessingInterval;
    }

    /**
     * Sets the value of the revisedProcessingInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRevisedProcessingInterval(Double value) {
        this.revisedProcessingInterval = value;
    }

    /**
     * Gets the value of the revisedAggregateConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link AggregateConfiguration }{@code >}
     *     
     */
    public JAXBElement<AggregateConfiguration> getRevisedAggregateConfiguration() {
        return revisedAggregateConfiguration;
    }

    /**
     * Sets the value of the revisedAggregateConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link AggregateConfiguration }{@code >}
     *     
     */
    public void setRevisedAggregateConfiguration(JAXBElement<AggregateConfiguration> value) {
        this.revisedAggregateConfiguration = value;
    }

}
