//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AxisInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AxisInformation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EngineeringUnits" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}EUInformation" minOccurs="0"/>
 *         &lt;element name="EURange" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}Range" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}LocalizedText" minOccurs="0"/>
 *         &lt;element name="AxisScaleType" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}AxisScaleEnumeration" minOccurs="0"/>
 *         &lt;element name="AxisSteps" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfDouble" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AxisInformation", propOrder = {
    "engineeringUnits",
    "euRange",
    "title",
    "axisScaleType",
    "axisSteps"
})
public class AxisInformation {

    @XmlElementRef(name = "EngineeringUnits", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<EUInformation> engineeringUnits;
    @XmlElementRef(name = "EURange", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<Range> euRange;
    @XmlElementRef(name = "Title", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<LocalizedText> title;
    @XmlElement(name = "AxisScaleType")
    @XmlSchemaType(name = "string")
    protected AxisScaleEnumeration axisScaleType;
    @XmlElementRef(name = "AxisSteps", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfDouble> axisSteps;

    /**
     * Gets the value of the engineeringUnits property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link EUInformation }{@code >}
     *     
     */
    public JAXBElement<EUInformation> getEngineeringUnits() {
        return engineeringUnits;
    }

    /**
     * Sets the value of the engineeringUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link EUInformation }{@code >}
     *     
     */
    public void setEngineeringUnits(JAXBElement<EUInformation> value) {
        this.engineeringUnits = value;
    }

    /**
     * Gets the value of the euRange property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Range }{@code >}
     *     
     */
    public JAXBElement<Range> getEURange() {
        return euRange;
    }

    /**
     * Sets the value of the euRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Range }{@code >}
     *     
     */
    public void setEURange(JAXBElement<Range> value) {
        this.euRange = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LocalizedText }{@code >}
     *     
     */
    public JAXBElement<LocalizedText> getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LocalizedText }{@code >}
     *     
     */
    public void setTitle(JAXBElement<LocalizedText> value) {
        this.title = value;
    }

    /**
     * Gets the value of the axisScaleType property.
     * 
     * @return
     *     possible object is
     *     {@link AxisScaleEnumeration }
     *     
     */
    public AxisScaleEnumeration getAxisScaleType() {
        return axisScaleType;
    }

    /**
     * Sets the value of the axisScaleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AxisScaleEnumeration }
     *     
     */
    public void setAxisScaleType(AxisScaleEnumeration value) {
        this.axisScaleType = value;
    }

    /**
     * Gets the value of the axisSteps property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfDouble }{@code >}
     *     
     */
    public JAXBElement<ListOfDouble> getAxisSteps() {
        return axisSteps;
    }

    /**
     * Sets the value of the axisSteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfDouble }{@code >}
     *     
     */
    public void setAxisSteps(JAXBElement<ListOfDouble> value) {
        this.axisSteps = value;
    }

}
