//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BrowseDirection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BrowseDirection">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Forward_0"/>
 *     &lt;enumeration value="Inverse_1"/>
 *     &lt;enumeration value="Both_2"/>
 *     &lt;enumeration value="Invalid_3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BrowseDirection")
@XmlEnum
public enum BrowseDirection {

    @XmlEnumValue("Forward_0")
    FORWARD_0("Forward_0"),
    @XmlEnumValue("Inverse_1")
    INVERSE_1("Inverse_1"),
    @XmlEnumValue("Both_2")
    BOTH_2("Both_2"),
    @XmlEnumValue("Invalid_3")
    INVALID_3("Invalid_3");
    private final String value;

    BrowseDirection(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BrowseDirection fromValue(String v) {
        for (BrowseDirection c: BrowseDirection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
