//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataTypeSchemaHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataTypeSchemaHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Namespaces" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfString" minOccurs="0"/>
 *         &lt;element name="StructureDataTypes" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfStructureDescription" minOccurs="0"/>
 *         &lt;element name="EnumDataTypes" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfEnumDescription" minOccurs="0"/>
 *         &lt;element name="SimpleDataTypes" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfSimpleTypeDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataTypeSchemaHeader", propOrder = {
    "namespaces",
    "structureDataTypes",
    "enumDataTypes",
    "simpleDataTypes"
})
@XmlSeeAlso({
    UABinaryFileDataType.class,
    DataSetMetaDataType.class
})
public class DataTypeSchemaHeader {

    @XmlElementRef(name = "Namespaces", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfString> namespaces;
    @XmlElementRef(name = "StructureDataTypes", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfStructureDescription> structureDataTypes;
    @XmlElementRef(name = "EnumDataTypes", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfEnumDescription> enumDataTypes;
    @XmlElementRef(name = "SimpleDataTypes", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfSimpleTypeDescription> simpleDataTypes;

    /**
     * Gets the value of the namespaces property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfString }{@code >}
     *     
     */
    public JAXBElement<ListOfString> getNamespaces() {
        return namespaces;
    }

    /**
     * Sets the value of the namespaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfString }{@code >}
     *     
     */
    public void setNamespaces(JAXBElement<ListOfString> value) {
        this.namespaces = value;
    }

    /**
     * Gets the value of the structureDataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfStructureDescription }{@code >}
     *     
     */
    public JAXBElement<ListOfStructureDescription> getStructureDataTypes() {
        return structureDataTypes;
    }

    /**
     * Sets the value of the structureDataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfStructureDescription }{@code >}
     *     
     */
    public void setStructureDataTypes(JAXBElement<ListOfStructureDescription> value) {
        this.structureDataTypes = value;
    }

    /**
     * Gets the value of the enumDataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfEnumDescription }{@code >}
     *     
     */
    public JAXBElement<ListOfEnumDescription> getEnumDataTypes() {
        return enumDataTypes;
    }

    /**
     * Sets the value of the enumDataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfEnumDescription }{@code >}
     *     
     */
    public void setEnumDataTypes(JAXBElement<ListOfEnumDescription> value) {
        this.enumDataTypes = value;
    }

    /**
     * Gets the value of the simpleDataTypes property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfSimpleTypeDescription }{@code >}
     *     
     */
    public JAXBElement<ListOfSimpleTypeDescription> getSimpleDataTypes() {
        return simpleDataTypes;
    }

    /**
     * Sets the value of the simpleDataTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfSimpleTypeDescription }{@code >}
     *     
     */
    public void setSimpleDataTypes(JAXBElement<ListOfSimpleTypeDescription> value) {
        this.simpleDataTypes = value;
    }

}
