//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DataChangeTrigger.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DataChangeTrigger">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Status_0"/>
 *     &lt;enumeration value="StatusValue_1"/>
 *     &lt;enumeration value="StatusValueTimestamp_2"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DataChangeTrigger")
@XmlEnum
public enum DataChangeTrigger {

    @XmlEnumValue("Status_0")
    STATUS_0("Status_0"),
    @XmlEnumValue("StatusValue_1")
    STATUS_VALUE_1("StatusValue_1"),
    @XmlEnumValue("StatusValueTimestamp_2")
    STATUS_VALUE_TIMESTAMP_2("StatusValueTimestamp_2");
    private final String value;

    DataChangeTrigger(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DataChangeTrigger fromValue(String v) {
        for (DataChangeTrigger c: DataChangeTrigger.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
