//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DatagramWriterGroupTransportDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatagramWriterGroupTransportDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}WriterGroupTransportDataType">
 *       &lt;sequence>
 *         &lt;element name="MessageRepeatCount" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *         &lt;element name="MessageRepeatDelay" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatagramWriterGroupTransportDataType", propOrder = {
    "messageRepeatCount",
    "messageRepeatDelay"
})
public class DatagramWriterGroupTransportDataType
    extends WriterGroupTransportDataType
{

    @XmlElement(name = "MessageRepeatCount")
    @XmlSchemaType(name = "unsignedByte")
    protected Short messageRepeatCount;
    @XmlElement(name = "MessageRepeatDelay")
    protected Double messageRepeatDelay;

    /**
     * Gets the value of the messageRepeatCount property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getMessageRepeatCount() {
        return messageRepeatCount;
    }

    /**
     * Sets the value of the messageRepeatCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setMessageRepeatCount(Short value) {
        this.messageRepeatCount = value;
    }

    /**
     * Gets the value of the messageRepeatDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMessageRepeatDelay() {
        return messageRepeatDelay;
    }

    /**
     * Sets the value of the messageRepeatDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMessageRepeatDelay(Double value) {
        this.messageRepeatDelay = value;
    }

}
