//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventFilterResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventFilterResult">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}MonitoringFilterResult">
 *       &lt;sequence>
 *         &lt;element name="SelectClauseResults" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfStatusCode" minOccurs="0"/>
 *         &lt;element name="SelectClauseDiagnosticInfos" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfDiagnosticInfo" minOccurs="0"/>
 *         &lt;element name="WhereClauseResult" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ContentFilterResult" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventFilterResult", propOrder = {
    "selectClauseResults",
    "selectClauseDiagnosticInfos",
    "whereClauseResult"
})
public class EventFilterResult
    extends MonitoringFilterResult
{

    @XmlElementRef(name = "SelectClauseResults", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfStatusCode> selectClauseResults;
    @XmlElementRef(name = "SelectClauseDiagnosticInfos", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfDiagnosticInfo> selectClauseDiagnosticInfos;
    @XmlElementRef(name = "WhereClauseResult", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ContentFilterResult> whereClauseResult;

    /**
     * Gets the value of the selectClauseResults property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfStatusCode }{@code >}
     *     
     */
    public JAXBElement<ListOfStatusCode> getSelectClauseResults() {
        return selectClauseResults;
    }

    /**
     * Sets the value of the selectClauseResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfStatusCode }{@code >}
     *     
     */
    public void setSelectClauseResults(JAXBElement<ListOfStatusCode> value) {
        this.selectClauseResults = value;
    }

    /**
     * Gets the value of the selectClauseDiagnosticInfos property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfDiagnosticInfo }{@code >}
     *     
     */
    public JAXBElement<ListOfDiagnosticInfo> getSelectClauseDiagnosticInfos() {
        return selectClauseDiagnosticInfos;
    }

    /**
     * Sets the value of the selectClauseDiagnosticInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfDiagnosticInfo }{@code >}
     *     
     */
    public void setSelectClauseDiagnosticInfos(JAXBElement<ListOfDiagnosticInfo> value) {
        this.selectClauseDiagnosticInfos = value;
    }

    /**
     * Gets the value of the whereClauseResult property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ContentFilterResult }{@code >}
     *     
     */
    public JAXBElement<ContentFilterResult> getWhereClauseResult() {
        return whereClauseResult;
    }

    /**
     * Sets the value of the whereClauseResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ContentFilterResult }{@code >}
     *     
     */
    public void setWhereClauseResult(JAXBElement<ContentFilterResult> value) {
        this.whereClauseResult = value;
    }

}
