//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HistoryModifiedData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HistoryModifiedData">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}HistoryData">
 *       &lt;sequence>
 *         &lt;element name="ModificationInfos" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfModificationInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HistoryModifiedData", propOrder = {
    "modificationInfos"
})
public class HistoryModifiedData
    extends HistoryData
{

    @XmlElementRef(name = "ModificationInfos", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfModificationInfo> modificationInfos;

    /**
     * Gets the value of the modificationInfos property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfModificationInfo }{@code >}
     *     
     */
    public JAXBElement<ListOfModificationInfo> getModificationInfos() {
        return modificationInfos;
    }

    /**
     * Sets the value of the modificationInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfModificationInfo }{@code >}
     *     
     */
    public void setModificationInfos(JAXBElement<ListOfModificationInfo> value) {
        this.modificationInfos = value;
    }

}
