//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdentityCriteriaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IdentityCriteriaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UserName_1"/>
 *     &lt;enumeration value="Thumbprint_2"/>
 *     &lt;enumeration value="Role_3"/>
 *     &lt;enumeration value="GroupId_4"/>
 *     &lt;enumeration value="Anonymous_5"/>
 *     &lt;enumeration value="AuthenticatedUser_6"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IdentityCriteriaType")
@XmlEnum
public enum IdentityCriteriaType {

    @XmlEnumValue("UserName_1")
    USER_NAME_1("UserName_1"),
    @XmlEnumValue("Thumbprint_2")
    THUMBPRINT_2("Thumbprint_2"),
    @XmlEnumValue("Role_3")
    ROLE_3("Role_3"),
    @XmlEnumValue("GroupId_4")
    GROUP_ID_4("GroupId_4"),
    @XmlEnumValue("Anonymous_5")
    ANONYMOUS_5("Anonymous_5"),
    @XmlEnumValue("AuthenticatedUser_6")
    AUTHENTICATED_USER_6("AuthenticatedUser_6");
    private final String value;

    IdentityCriteriaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdentityCriteriaType fromValue(String v) {
        for (IdentityCriteriaType c: IdentityCriteriaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
