//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IdType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IdType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Numeric_0"/>
 *     &lt;enumeration value="String_1"/>
 *     &lt;enumeration value="Guid_2"/>
 *     &lt;enumeration value="Opaque_3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IdType")
@XmlEnum
public enum IdType {

    @XmlEnumValue("Numeric_0")
    NUMERIC_0("Numeric_0"),
    @XmlEnumValue("String_1")
    STRING_1("String_1"),
    @XmlEnumValue("Guid_2")
    GUID_2("Guid_2"),
    @XmlEnumValue("Opaque_3")
    OPAQUE_3("Opaque_3");
    private final String value;

    IdType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IdType fromValue(String v) {
        for (IdType c: IdType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
