//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ListOfDataSetReaderMessageDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListOfDataSetReaderMessageDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DataSetReaderMessageDataType" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}DataSetReaderMessageDataType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListOfDataSetReaderMessageDataType", propOrder = {
    "dataSetReaderMessageDataType"
})
public class ListOfDataSetReaderMessageDataType {

    @XmlElement(name = "DataSetReaderMessageDataType", nillable = true)
    protected List<DataSetReaderMessageDataType> dataSetReaderMessageDataType;

    /**
     * Gets the value of the dataSetReaderMessageDataType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dataSetReaderMessageDataType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDataSetReaderMessageDataType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DataSetReaderMessageDataType }
     * 
     * 
     */
    public List<DataSetReaderMessageDataType> getDataSetReaderMessageDataType() {
        if (dataSetReaderMessageDataType == null) {
            dataSetReaderMessageDataType = new ArrayList<DataSetReaderMessageDataType>();
        }
        return this.dataSetReaderMessageDataType;
    }

}
