//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeAttributesMask.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NodeAttributesMask">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None_0"/>
 *     &lt;enumeration value="AccessLevel_1"/>
 *     &lt;enumeration value="ArrayDimensions_2"/>
 *     &lt;enumeration value="BrowseName_4"/>
 *     &lt;enumeration value="ContainsNoLoops_8"/>
 *     &lt;enumeration value="DataType_16"/>
 *     &lt;enumeration value="Description_32"/>
 *     &lt;enumeration value="DisplayName_64"/>
 *     &lt;enumeration value="EventNotifier_128"/>
 *     &lt;enumeration value="Executable_256"/>
 *     &lt;enumeration value="Historizing_512"/>
 *     &lt;enumeration value="InverseName_1024"/>
 *     &lt;enumeration value="IsAbstract_2048"/>
 *     &lt;enumeration value="MinimumSamplingInterval_4096"/>
 *     &lt;enumeration value="NodeClass_8192"/>
 *     &lt;enumeration value="NodeId_16384"/>
 *     &lt;enumeration value="Symmetric_32768"/>
 *     &lt;enumeration value="UserAccessLevel_65536"/>
 *     &lt;enumeration value="UserExecutable_131072"/>
 *     &lt;enumeration value="UserWriteMask_262144"/>
 *     &lt;enumeration value="ValueRank_524288"/>
 *     &lt;enumeration value="WriteMask_1048576"/>
 *     &lt;enumeration value="Value_2097152"/>
 *     &lt;enumeration value="DataTypeDefinition_4194304"/>
 *     &lt;enumeration value="RolePermissions_8388608"/>
 *     &lt;enumeration value="AccessRestrictions_16777216"/>
 *     &lt;enumeration value="All_33554431"/>
 *     &lt;enumeration value="BaseNode_26501220"/>
 *     &lt;enumeration value="Object_26501348"/>
 *     &lt;enumeration value="ObjectType_26503268"/>
 *     &lt;enumeration value="Variable_26571383"/>
 *     &lt;enumeration value="VariableType_28600438"/>
 *     &lt;enumeration value="Method_26632548"/>
 *     &lt;enumeration value="ReferenceType_26537060"/>
 *     &lt;enumeration value="View_26501356"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NodeAttributesMask")
@XmlEnum
public enum NodeAttributesMask {

    @XmlEnumValue("None_0")
    NONE_0("None_0"),
    @XmlEnumValue("AccessLevel_1")
    ACCESS_LEVEL_1("AccessLevel_1"),
    @XmlEnumValue("ArrayDimensions_2")
    ARRAY_DIMENSIONS_2("ArrayDimensions_2"),
    @XmlEnumValue("BrowseName_4")
    BROWSE_NAME_4("BrowseName_4"),
    @XmlEnumValue("ContainsNoLoops_8")
    CONTAINS_NO_LOOPS_8("ContainsNoLoops_8"),
    @XmlEnumValue("DataType_16")
    DATA_TYPE_16("DataType_16"),
    @XmlEnumValue("Description_32")
    DESCRIPTION_32("Description_32"),
    @XmlEnumValue("DisplayName_64")
    DISPLAY_NAME_64("DisplayName_64"),
    @XmlEnumValue("EventNotifier_128")
    EVENT_NOTIFIER_128("EventNotifier_128"),
    @XmlEnumValue("Executable_256")
    EXECUTABLE_256("Executable_256"),
    @XmlEnumValue("Historizing_512")
    HISTORIZING_512("Historizing_512"),
    @XmlEnumValue("InverseName_1024")
    INVERSE_NAME_1024("InverseName_1024"),
    @XmlEnumValue("IsAbstract_2048")
    IS_ABSTRACT_2048("IsAbstract_2048"),
    @XmlEnumValue("MinimumSamplingInterval_4096")
    MINIMUM_SAMPLING_INTERVAL_4096("MinimumSamplingInterval_4096"),
    @XmlEnumValue("NodeClass_8192")
    NODE_CLASS_8192("NodeClass_8192"),
    @XmlEnumValue("NodeId_16384")
    NODE_ID_16384("NodeId_16384"),
    @XmlEnumValue("Symmetric_32768")
    SYMMETRIC_32768("Symmetric_32768"),
    @XmlEnumValue("UserAccessLevel_65536")
    USER_ACCESS_LEVEL_65536("UserAccessLevel_65536"),
    @XmlEnumValue("UserExecutable_131072")
    USER_EXECUTABLE_131072("UserExecutable_131072"),
    @XmlEnumValue("UserWriteMask_262144")
    USER_WRITE_MASK_262144("UserWriteMask_262144"),
    @XmlEnumValue("ValueRank_524288")
    VALUE_RANK_524288("ValueRank_524288"),
    @XmlEnumValue("WriteMask_1048576")
    WRITE_MASK_1048576("WriteMask_1048576"),
    @XmlEnumValue("Value_2097152")
    VALUE_2097152("Value_2097152"),
    @XmlEnumValue("DataTypeDefinition_4194304")
    DATA_TYPE_DEFINITION_4194304("DataTypeDefinition_4194304"),
    @XmlEnumValue("RolePermissions_8388608")
    ROLE_PERMISSIONS_8388608("RolePermissions_8388608"),
    @XmlEnumValue("AccessRestrictions_16777216")
    ACCESS_RESTRICTIONS_16777216("AccessRestrictions_16777216"),
    @XmlEnumValue("All_33554431")
    ALL_33554431("All_33554431"),
    @XmlEnumValue("BaseNode_26501220")
    BASE_NODE_26501220("BaseNode_26501220"),
    @XmlEnumValue("Object_26501348")
    OBJECT_26501348("Object_26501348"),
    @XmlEnumValue("ObjectType_26503268")
    OBJECT_TYPE_26503268("ObjectType_26503268"),
    @XmlEnumValue("Variable_26571383")
    VARIABLE_26571383("Variable_26571383"),
    @XmlEnumValue("VariableType_28600438")
    VARIABLE_TYPE_28600438("VariableType_28600438"),
    @XmlEnumValue("Method_26632548")
    METHOD_26632548("Method_26632548"),
    @XmlEnumValue("ReferenceType_26537060")
    REFERENCE_TYPE_26537060("ReferenceType_26537060"),
    @XmlEnumValue("View_26501356")
    VIEW_26501356("View_26501356");
    private final String value;

    NodeAttributesMask(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NodeAttributesMask fromValue(String v) {
        for (NodeAttributesMask c: NodeAttributesMask.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
