//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeTypeDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NodeTypeDescription">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TypeDefinitionNode" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ExpandedNodeId" minOccurs="0"/>
 *         &lt;element name="IncludeSubTypes" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DataToReturn" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfQueryDataDescription" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NodeTypeDescription", propOrder = {
    "typeDefinitionNode",
    "includeSubTypes",
    "dataToReturn"
})
public class NodeTypeDescription {

    @XmlElementRef(name = "TypeDefinitionNode", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ExpandedNodeId> typeDefinitionNode;
    @XmlElement(name = "IncludeSubTypes")
    protected Boolean includeSubTypes;
    @XmlElementRef(name = "DataToReturn", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfQueryDataDescription> dataToReturn;

    /**
     * Gets the value of the typeDefinitionNode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ExpandedNodeId }{@code >}
     *     
     */
    public JAXBElement<ExpandedNodeId> getTypeDefinitionNode() {
        return typeDefinitionNode;
    }

    /**
     * Sets the value of the typeDefinitionNode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ExpandedNodeId }{@code >}
     *     
     */
    public void setTypeDefinitionNode(JAXBElement<ExpandedNodeId> value) {
        this.typeDefinitionNode = value;
    }

    /**
     * Gets the value of the includeSubTypes property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIncludeSubTypes() {
        return includeSubTypes;
    }

    /**
     * Sets the value of the includeSubTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIncludeSubTypes(Boolean value) {
        this.includeSubTypes = value;
    }

    /**
     * Gets the value of the dataToReturn property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfQueryDataDescription }{@code >}
     *     
     */
    public JAXBElement<ListOfQueryDataDescription> getDataToReturn() {
        return dataToReturn;
    }

    /**
     * Sets the value of the dataToReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfQueryDataDescription }{@code >}
     *     
     */
    public void setDataToReturn(JAXBElement<ListOfQueryDataDescription> value) {
        this.dataToReturn = value;
    }

}
