//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Node complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Node">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NodeId" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}NodeId" minOccurs="0"/>
 *         &lt;element name="NodeClass" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}NodeClass" minOccurs="0"/>
 *         &lt;element name="BrowseName" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}QualifiedName" minOccurs="0"/>
 *         &lt;element name="DisplayName" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}LocalizedText" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}LocalizedText" minOccurs="0"/>
 *         &lt;element name="WriteMask" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="UserWriteMask" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="RolePermissions" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfRolePermissionType" minOccurs="0"/>
 *         &lt;element name="UserRolePermissions" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfRolePermissionType" minOccurs="0"/>
 *         &lt;element name="AccessRestrictions" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="References" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfReferenceNode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Node", propOrder = {
    "nodeId",
    "nodeClass",
    "browseName",
    "displayName",
    "description",
    "writeMask",
    "userWriteMask",
    "rolePermissions",
    "userRolePermissions",
    "accessRestrictions",
    "references"
})
@XmlSeeAlso({
    InstanceNode.class,
    TypeNode.class
})
public class Node {

    @XmlElementRef(name = "NodeId", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<NodeId> nodeId;
    @XmlElement(name = "NodeClass")
    @XmlSchemaType(name = "string")
    protected NodeClass nodeClass;
    @XmlElementRef(name = "BrowseName", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<QualifiedName> browseName;
    @XmlElementRef(name = "DisplayName", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<LocalizedText> displayName;
    @XmlElementRef(name = "Description", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<LocalizedText> description;
    @XmlElement(name = "WriteMask")
    @XmlSchemaType(name = "unsignedInt")
    protected Long writeMask;
    @XmlElement(name = "UserWriteMask")
    @XmlSchemaType(name = "unsignedInt")
    protected Long userWriteMask;
    @XmlElementRef(name = "RolePermissions", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfRolePermissionType> rolePermissions;
    @XmlElementRef(name = "UserRolePermissions", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfRolePermissionType> userRolePermissions;
    @XmlElement(name = "AccessRestrictions")
    @XmlSchemaType(name = "unsignedShort")
    protected Integer accessRestrictions;
    @XmlElementRef(name = "References", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfReferenceNode> references;

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NodeId }{@code >}
     *     
     */
    public JAXBElement<NodeId> getNodeId() {
        return nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NodeId }{@code >}
     *     
     */
    public void setNodeId(JAXBElement<NodeId> value) {
        this.nodeId = value;
    }

    /**
     * Gets the value of the nodeClass property.
     * 
     * @return
     *     possible object is
     *     {@link NodeClass }
     *     
     */
    public NodeClass getNodeClass() {
        return nodeClass;
    }

    /**
     * Sets the value of the nodeClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeClass }
     *     
     */
    public void setNodeClass(NodeClass value) {
        this.nodeClass = value;
    }

    /**
     * Gets the value of the browseName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link QualifiedName }{@code >}
     *     
     */
    public JAXBElement<QualifiedName> getBrowseName() {
        return browseName;
    }

    /**
     * Sets the value of the browseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link QualifiedName }{@code >}
     *     
     */
    public void setBrowseName(JAXBElement<QualifiedName> value) {
        this.browseName = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LocalizedText }{@code >}
     *     
     */
    public JAXBElement<LocalizedText> getDisplayName() {
        return displayName;
    }

    /**
     * Sets the value of the displayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LocalizedText }{@code >}
     *     
     */
    public void setDisplayName(JAXBElement<LocalizedText> value) {
        this.displayName = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link LocalizedText }{@code >}
     *     
     */
    public JAXBElement<LocalizedText> getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link LocalizedText }{@code >}
     *     
     */
    public void setDescription(JAXBElement<LocalizedText> value) {
        this.description = value;
    }

    /**
     * Gets the value of the writeMask property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWriteMask() {
        return writeMask;
    }

    /**
     * Sets the value of the writeMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWriteMask(Long value) {
        this.writeMask = value;
    }

    /**
     * Gets the value of the userWriteMask property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getUserWriteMask() {
        return userWriteMask;
    }

    /**
     * Sets the value of the userWriteMask property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setUserWriteMask(Long value) {
        this.userWriteMask = value;
    }

    /**
     * Gets the value of the rolePermissions property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfRolePermissionType }{@code >}
     *     
     */
    public JAXBElement<ListOfRolePermissionType> getRolePermissions() {
        return rolePermissions;
    }

    /**
     * Sets the value of the rolePermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfRolePermissionType }{@code >}
     *     
     */
    public void setRolePermissions(JAXBElement<ListOfRolePermissionType> value) {
        this.rolePermissions = value;
    }

    /**
     * Gets the value of the userRolePermissions property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfRolePermissionType }{@code >}
     *     
     */
    public JAXBElement<ListOfRolePermissionType> getUserRolePermissions() {
        return userRolePermissions;
    }

    /**
     * Sets the value of the userRolePermissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfRolePermissionType }{@code >}
     *     
     */
    public void setUserRolePermissions(JAXBElement<ListOfRolePermissionType> value) {
        this.userRolePermissions = value;
    }

    /**
     * Gets the value of the accessRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccessRestrictions() {
        return accessRestrictions;
    }

    /**
     * Sets the value of the accessRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccessRestrictions(Integer value) {
        this.accessRestrictions = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfReferenceNode }{@code >}
     *     
     */
    public JAXBElement<ListOfReferenceNode> getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfReferenceNode }{@code >}
     *     
     */
    public void setReferences(JAXBElement<ListOfReferenceNode> value) {
        this.references = value;
    }

}
