//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PublishedVariableDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublishedVariableDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PublishedVariable" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}NodeId" minOccurs="0"/>
 *         &lt;element name="AttributeId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="SamplingIntervalHint" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="DeadbandType" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="DeadbandValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="IndexRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SubstituteValue" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}Variant" minOccurs="0"/>
 *         &lt;element name="MetaDataProperties" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfQualifiedName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublishedVariableDataType", propOrder = {
    "publishedVariable",
    "attributeId",
    "samplingIntervalHint",
    "deadbandType",
    "deadbandValue",
    "indexRange",
    "substituteValue",
    "metaDataProperties"
})
public class PublishedVariableDataType {

    @XmlElementRef(name = "PublishedVariable", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<NodeId> publishedVariable;
    @XmlElement(name = "AttributeId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long attributeId;
    @XmlElement(name = "SamplingIntervalHint")
    protected Double samplingIntervalHint;
    @XmlElement(name = "DeadbandType")
    @XmlSchemaType(name = "unsignedInt")
    protected Long deadbandType;
    @XmlElement(name = "DeadbandValue")
    protected Double deadbandValue;
    @XmlElementRef(name = "IndexRange", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<String> indexRange;
    @XmlElement(name = "SubstituteValue")
    protected Variant substituteValue;
    @XmlElementRef(name = "MetaDataProperties", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfQualifiedName> metaDataProperties;

    /**
     * Gets the value of the publishedVariable property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NodeId }{@code >}
     *     
     */
    public JAXBElement<NodeId> getPublishedVariable() {
        return publishedVariable;
    }

    /**
     * Sets the value of the publishedVariable property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NodeId }{@code >}
     *     
     */
    public void setPublishedVariable(JAXBElement<NodeId> value) {
        this.publishedVariable = value;
    }

    /**
     * Gets the value of the attributeId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getAttributeId() {
        return attributeId;
    }

    /**
     * Sets the value of the attributeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setAttributeId(Long value) {
        this.attributeId = value;
    }

    /**
     * Gets the value of the samplingIntervalHint property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSamplingIntervalHint() {
        return samplingIntervalHint;
    }

    /**
     * Sets the value of the samplingIntervalHint property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSamplingIntervalHint(Double value) {
        this.samplingIntervalHint = value;
    }

    /**
     * Gets the value of the deadbandType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDeadbandType() {
        return deadbandType;
    }

    /**
     * Sets the value of the deadbandType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDeadbandType(Long value) {
        this.deadbandType = value;
    }

    /**
     * Gets the value of the deadbandValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDeadbandValue() {
        return deadbandValue;
    }

    /**
     * Sets the value of the deadbandValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDeadbandValue(Double value) {
        this.deadbandValue = value;
    }

    /**
     * Gets the value of the indexRange property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getIndexRange() {
        return indexRange;
    }

    /**
     * Sets the value of the indexRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setIndexRange(JAXBElement<String> value) {
        this.indexRange = value;
    }

    /**
     * Gets the value of the substituteValue property.
     * 
     * @return
     *     possible object is
     *     {@link Variant }
     *     
     */
    public Variant getSubstituteValue() {
        return substituteValue;
    }

    /**
     * Sets the value of the substituteValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Variant }
     *     
     */
    public void setSubstituteValue(Variant value) {
        this.substituteValue = value;
    }

    /**
     * Gets the value of the metaDataProperties property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfQualifiedName }{@code >}
     *     
     */
    public JAXBElement<ListOfQualifiedName> getMetaDataProperties() {
        return metaDataProperties;
    }

    /**
     * Sets the value of the metaDataProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfQualifiedName }{@code >}
     *     
     */
    public void setMetaDataProperties(JAXBElement<ListOfQualifiedName> value) {
        this.metaDataProperties = value;
    }

}
