//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PubSubState.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PubSubState">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Disabled_0"/>
 *     &lt;enumeration value="Paused_1"/>
 *     &lt;enumeration value="Operational_2"/>
 *     &lt;enumeration value="Error_3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PubSubState")
@XmlEnum
public enum PubSubState {

    @XmlEnumValue("Disabled_0")
    DISABLED_0("Disabled_0"),
    @XmlEnumValue("Paused_1")
    PAUSED_1("Paused_1"),
    @XmlEnumValue("Operational_2")
    OPERATIONAL_2("Operational_2"),
    @XmlEnumValue("Error_3")
    ERROR_3("Error_3");
    private final String value;

    PubSubState(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PubSubState fromValue(String v) {
        for (PubSubState c: PubSubState.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
