//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PubSubDiagnosticsCounterClassification.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PubSubDiagnosticsCounterClassification">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Information_0"/>
 *     &lt;enumeration value="Error_1"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PubSubDiagnosticsCounterClassification")
@XmlEnum
public enum PubSubDiagnosticsCounterClassification {

    @XmlEnumValue("Information_0")
    INFORMATION_0("Information_0"),
    @XmlEnumValue("Error_1")
    ERROR_1("Error_1");
    private final String value;

    PubSubDiagnosticsCounterClassification(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PubSubDiagnosticsCounterClassification fromValue(String v) {
        for (PubSubDiagnosticsCounterClassification c: PubSubDiagnosticsCounterClassification.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
