//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityTokenRequestType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SecurityTokenRequestType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Issue_0"/>
 *     &lt;enumeration value="Renew_1"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SecurityTokenRequestType")
@XmlEnum
public enum SecurityTokenRequestType {

    @XmlEnumValue("Issue_0")
    ISSUE_0("Issue_0"),
    @XmlEnumValue("Renew_1")
    RENEW_1("Renew_1");
    private final String value;

    SecurityTokenRequestType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SecurityTokenRequestType fromValue(String v) {
        for (SecurityTokenRequestType c: SecurityTokenRequestType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
