//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StructureDescription complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StructureDescription">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}DataTypeDescription">
 *       &lt;sequence>
 *         &lt;element name="StructureDefinition" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}StructureDefinition" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StructureDescription", propOrder = {
    "structureDefinition"
})
public class StructureDescription
    extends DataTypeDescription
{

    @XmlElementRef(name = "StructureDefinition", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<StructureDefinition> structureDefinition;

    /**
     * Gets the value of the structureDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link StructureDefinition }{@code >}
     *     
     */
    public JAXBElement<StructureDefinition> getStructureDefinition() {
        return structureDefinition;
    }

    /**
     * Sets the value of the structureDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link StructureDefinition }{@code >}
     *     
     */
    public void setStructureDefinition(JAXBElement<StructureDefinition> value) {
        this.structureDefinition = value;
    }

}
