//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ThreeDFrame complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ThreeDFrame">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}Frame">
 *       &lt;sequence>
 *         &lt;element name="CartesianCoordinates" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ThreeDCartesianCoordinates" minOccurs="0"/>
 *         &lt;element name="Orientation" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ThreeDOrientation" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ThreeDFrame", propOrder = {
    "cartesianCoordinates",
    "orientation"
})
public class ThreeDFrame
    extends Frame
{

    @XmlElementRef(name = "CartesianCoordinates", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ThreeDCartesianCoordinates> cartesianCoordinates;
    @XmlElementRef(name = "Orientation", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ThreeDOrientation> orientation;

    /**
     * Gets the value of the cartesianCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ThreeDCartesianCoordinates }{@code >}
     *     
     */
    public JAXBElement<ThreeDCartesianCoordinates> getCartesianCoordinates() {
        return cartesianCoordinates;
    }

    /**
     * Sets the value of the cartesianCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ThreeDCartesianCoordinates }{@code >}
     *     
     */
    public void setCartesianCoordinates(JAXBElement<ThreeDCartesianCoordinates> value) {
        this.cartesianCoordinates = value;
    }

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ThreeDOrientation }{@code >}
     *     
     */
    public JAXBElement<ThreeDOrientation> getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ThreeDOrientation }{@code >}
     *     
     */
    public void setOrientation(JAXBElement<ThreeDOrientation> value) {
        this.orientation = value;
    }

}
