//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimestampsToReturn.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TimestampsToReturn">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Source_0"/>
 *     &lt;enumeration value="Server_1"/>
 *     &lt;enumeration value="Both_2"/>
 *     &lt;enumeration value="Neither_3"/>
 *     &lt;enumeration value="Invalid_4"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TimestampsToReturn")
@XmlEnum
public enum TimestampsToReturn {

    @XmlEnumValue("Source_0")
    SOURCE_0("Source_0"),
    @XmlEnumValue("Server_1")
    SERVER_1("Server_1"),
    @XmlEnumValue("Both_2")
    BOTH_2("Both_2"),
    @XmlEnumValue("Neither_3")
    NEITHER_3("Neither_3"),
    @XmlEnumValue("Invalid_4")
    INVALID_4("Invalid_4");
    private final String value;

    TimestampsToReturn(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TimestampsToReturn fromValue(String v) {
        for (TimestampsToReturn c: TimestampsToReturn.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
