//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrustListMasks.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrustListMasks">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="None_0"/>
 *     &lt;enumeration value="TrustedCertificates_1"/>
 *     &lt;enumeration value="TrustedCrls_2"/>
 *     &lt;enumeration value="IssuerCertificates_4"/>
 *     &lt;enumeration value="IssuerCrls_8"/>
 *     &lt;enumeration value="All_15"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TrustListMasks")
@XmlEnum
public enum TrustListMasks {

    @XmlEnumValue("None_0")
    NONE_0("None_0"),
    @XmlEnumValue("TrustedCertificates_1")
    TRUSTED_CERTIFICATES_1("TrustedCertificates_1"),
    @XmlEnumValue("TrustedCrls_2")
    TRUSTED_CRLS_2("TrustedCrls_2"),
    @XmlEnumValue("IssuerCertificates_4")
    ISSUER_CERTIFICATES_4("IssuerCertificates_4"),
    @XmlEnumValue("IssuerCrls_8")
    ISSUER_CRLS_8("IssuerCrls_8"),
    @XmlEnumValue("All_15")
    ALL_15("All_15");
    private final String value;

    TrustListMasks(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrustListMasks fromValue(String v) {
        for (TrustListMasks c: TrustListMasks.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
