//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UpdateEventDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateEventDetails">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}HistoryUpdateDetails">
 *       &lt;sequence>
 *         &lt;element name="PerformInsertReplace" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}PerformUpdateType" minOccurs="0"/>
 *         &lt;element name="Filter" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}EventFilter" minOccurs="0"/>
 *         &lt;element name="EventData" type="{http://opcfoundation.org/UA/2008/02/Types.xsd}ListOfHistoryEventFieldList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateEventDetails", propOrder = {
    "performInsertReplace",
    "filter",
    "eventData"
})
public class UpdateEventDetails
    extends HistoryUpdateDetails
{

    @XmlElement(name = "PerformInsertReplace")
    @XmlSchemaType(name = "string")
    protected PerformUpdateType performInsertReplace;
    @XmlElementRef(name = "Filter", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<EventFilter> filter;
    @XmlElementRef(name = "EventData", namespace = "http://opcfoundation.org/UA/2008/02/Types.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<ListOfHistoryEventFieldList> eventData;

    /**
     * Gets the value of the performInsertReplace property.
     * 
     * @return
     *     possible object is
     *     {@link PerformUpdateType }
     *     
     */
    public PerformUpdateType getPerformInsertReplace() {
        return performInsertReplace;
    }

    /**
     * Sets the value of the performInsertReplace property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerformUpdateType }
     *     
     */
    public void setPerformInsertReplace(PerformUpdateType value) {
        this.performInsertReplace = value;
    }

    /**
     * Gets the value of the filter property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link EventFilter }{@code >}
     *     
     */
    public JAXBElement<EventFilter> getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link EventFilter }{@code >}
     *     
     */
    public void setFilter(JAXBElement<EventFilter> value) {
        this.filter = value;
    }

    /**
     * Gets the value of the eventData property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link ListOfHistoryEventFieldList }{@code >}
     *     
     */
    public JAXBElement<ListOfHistoryEventFieldList> getEventData() {
        return eventData;
    }

    /**
     * Sets the value of the eventData property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link ListOfHistoryEventFieldList }{@code >}
     *     
     */
    public void setEventData(JAXBElement<ListOfHistoryEventFieldList> value) {
        this.eventData = value;
    }

}
