//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 09:01:50 AM CEST 
//


package org.opcfoundation.ua._2008._02.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ViewAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ViewAttributes">
 *   &lt;complexContent>
 *     &lt;extension base="{http://opcfoundation.org/UA/2008/02/Types.xsd}NodeAttributes">
 *       &lt;sequence>
 *         &lt;element name="ContainsNoLoops" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EventNotifier" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ViewAttributes", propOrder = {
    "containsNoLoops",
    "eventNotifier"
})
public class ViewAttributes
    extends NodeAttributes
{

    @XmlElement(name = "ContainsNoLoops")
    protected Boolean containsNoLoops;
    @XmlElement(name = "EventNotifier")
    @XmlSchemaType(name = "unsignedByte")
    protected Short eventNotifier;

    /**
     * Gets the value of the containsNoLoops property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContainsNoLoops() {
        return containsNoLoops;
    }

    /**
     * Sets the value of the containsNoLoops property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContainsNoLoops(Boolean value) {
        this.containsNoLoops = value;
    }

    /**
     * Gets the value of the eventNotifier property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getEventNotifier() {
        return eventNotifier;
    }

    /**
     * Sets the value of the eventNotifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setEventNotifier(Short value) {
        this.eventNotifier = value;
    }

}
