//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.13 at 09:39:13 AM CEST 
//


package org.opcfoundation.ua._2011._03.uanodeset;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opcfoundation.ua._2011._03.uanodeset package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opcfoundation.ua._2011._03.uanodeset
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UAVariableType }
     * 
     */
    public UAVariableType createUAVariableType() {
        return new UAVariableType();
    }

    /**
     * Create an instance of {@link UAVariable }
     * 
     */
    public UAVariable createUAVariable() {
        return new UAVariable();
    }

    /**
     * Create an instance of {@link ListOfExtensions }
     * 
     */
    public ListOfExtensions createListOfExtensions() {
        return new ListOfExtensions();
    }

    /**
     * Create an instance of {@link UANodeSet }
     * 
     */
    public UANodeSet createUANodeSet() {
        return new UANodeSet();
    }

    /**
     * Create an instance of {@link UriTable }
     * 
     */
    public UriTable createUriTable() {
        return new UriTable();
    }

    /**
     * Create an instance of {@link ModelTable }
     * 
     */
    public ModelTable createModelTable() {
        return new ModelTable();
    }

    /**
     * Create an instance of {@link AliasTable }
     * 
     */
    public AliasTable createAliasTable() {
        return new AliasTable();
    }

    /**
     * Create an instance of {@link UAObject }
     * 
     */
    public UAObject createUAObject() {
        return new UAObject();
    }

    /**
     * Create an instance of {@link UAMethod }
     * 
     */
    public UAMethod createUAMethod() {
        return new UAMethod();
    }

    /**
     * Create an instance of {@link UAView }
     * 
     */
    public UAView createUAView() {
        return new UAView();
    }

    /**
     * Create an instance of {@link UAObjectType }
     * 
     */
    public UAObjectType createUAObjectType() {
        return new UAObjectType();
    }

    /**
     * Create an instance of {@link UADataType }
     * 
     */
    public UADataType createUADataType() {
        return new UADataType();
    }

    /**
     * Create an instance of {@link UAReferenceType }
     * 
     */
    public UAReferenceType createUAReferenceType() {
        return new UAReferenceType();
    }

    /**
     * Create an instance of {@link UANodeSetChangesStatus }
     * 
     */
    public UANodeSetChangesStatus createUANodeSetChangesStatus() {
        return new UANodeSetChangesStatus();
    }

    /**
     * Create an instance of {@link NodeSetStatusList }
     * 
     */
    public NodeSetStatusList createNodeSetStatusList() {
        return new NodeSetStatusList();
    }

    /**
     * Create an instance of {@link UANodeSetChanges }
     * 
     */
    public UANodeSetChanges createUANodeSetChanges() {
        return new UANodeSetChanges();
    }

    /**
     * Create an instance of {@link NodesToAdd }
     * 
     */
    public NodesToAdd createNodesToAdd() {
        return new NodesToAdd();
    }

    /**
     * Create an instance of {@link ReferencesToChange }
     * 
     */
    public ReferencesToChange createReferencesToChange() {
        return new ReferencesToChange();
    }

    /**
     * Create an instance of {@link NodesToDelete }
     * 
     */
    public NodesToDelete createNodesToDelete() {
        return new NodesToDelete();
    }

    /**
     * Create an instance of {@link ListOfReferences }
     * 
     */
    public ListOfReferences createListOfReferences() {
        return new ListOfReferences();
    }

    /**
     * Create an instance of {@link ReferenceChange }
     * 
     */
    public ReferenceChange createReferenceChange() {
        return new ReferenceChange();
    }

    /**
     * Create an instance of {@link UAMethodArgument }
     * 
     */
    public UAMethodArgument createUAMethodArgument() {
        return new UAMethodArgument();
    }

    /**
     * Create an instance of {@link DataTypeDefinition }
     * 
     */
    public DataTypeDefinition createDataTypeDefinition() {
        return new DataTypeDefinition();
    }

    /**
     * Create an instance of {@link LocalizedText }
     * 
     */
    public LocalizedText createLocalizedText() {
        return new LocalizedText();
    }

    /**
     * Create an instance of {@link TranslationType }
     * 
     */
    public TranslationType createTranslationType() {
        return new TranslationType();
    }

    /**
     * Create an instance of {@link NodeIdAlias }
     * 
     */
    public NodeIdAlias createNodeIdAlias() {
        return new NodeIdAlias();
    }

    /**
     * Create an instance of {@link UAType }
     * 
     */
    public UAType createUAType() {
        return new UAType();
    }

    /**
     * Create an instance of {@link DataTypeField }
     * 
     */
    public DataTypeField createDataTypeField() {
        return new DataTypeField();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link StructureTranslationType }
     * 
     */
    public StructureTranslationType createStructureTranslationType() {
        return new StructureTranslationType();
    }

    /**
     * Create an instance of {@link UANode }
     * 
     */
    public UANode createUANode() {
        return new UANode();
    }

    /**
     * Create an instance of {@link UAInstance }
     * 
     */
    public UAInstance createUAInstance() {
        return new UAInstance();
    }

    /**
     * Create an instance of {@link NodeToDelete }
     * 
     */
    public NodeToDelete createNodeToDelete() {
        return new NodeToDelete();
    }

    /**
     * Create an instance of {@link ModelTableEntry }
     * 
     */
    public ModelTableEntry createModelTableEntry() {
        return new ModelTableEntry();
    }

    /**
     * Create an instance of {@link RolePermission }
     * 
     */
    public RolePermission createRolePermission() {
        return new RolePermission();
    }

    /**
     * Create an instance of {@link NodeSetStatus }
     * 
     */
    public NodeSetStatus createNodeSetStatus() {
        return new NodeSetStatus();
    }

    /**
     * Create an instance of {@link ListOfRolePermissions }
     * 
     */
    public ListOfRolePermissions createListOfRolePermissions() {
        return new ListOfRolePermissions();
    }

    /**
     * Create an instance of {@link UAVariableType.Value }
     * 
     */
    public UAVariableType.Value createUAVariableTypeValue() {
        return new UAVariableType.Value();
    }

    /**
     * Create an instance of {@link UAVariable.Value }
     * 
     */
    public UAVariable.Value createUAVariableValue() {
        return new UAVariable.Value();
    }

    /**
     * Create an instance of {@link ListOfExtensions.Extension }
     * 
     */
    public ListOfExtensions.Extension createListOfExtensionsExtension() {
        return new ListOfExtensions.Extension();
    }

}
