//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.13 at 09:39:13 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://opcfoundation.org/UA/2011/03/UANodeSet.xsd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.opcfoundation.ua._2011._03.uanodeset;
