//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.13 at 09:39:13 AM CEST 
//


package org.opcfoundation.ua._2011._03.uanodeset;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NamespaceUris" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UriTable" minOccurs="0"/>
 *         &lt;element name="ServerUris" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}UriTable" minOccurs="0"/>
 *         &lt;element name="Aliases" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}AliasTable" minOccurs="0"/>
 *         &lt;element name="Extensions" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ListOfExtensions" minOccurs="0"/>
 *         &lt;element name="NodesToAdd" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}NodesToAdd" minOccurs="0"/>
 *         &lt;element name="ReferencesToAdd" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ReferencesToChange" minOccurs="0"/>
 *         &lt;element name="NodesToDelete" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}NodesToDelete" minOccurs="0"/>
 *         &lt;element name="ReferencesToDelete" type="{http://opcfoundation.org/UA/2011/03/UANodeSet.xsd}ReferencesToChange" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="LastModified" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="TransactionId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AcceptAllOrNothing" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "namespaceUris",
    "serverUris",
    "aliases",
    "extensions",
    "nodesToAdd",
    "referencesToAdd",
    "nodesToDelete",
    "referencesToDelete"
})
@XmlRootElement(name = "UANodeSetChanges")
public class UANodeSetChanges {

    @XmlElement(name = "NamespaceUris")
    protected UriTable namespaceUris;
    @XmlElement(name = "ServerUris")
    protected UriTable serverUris;
    @XmlElement(name = "Aliases")
    protected AliasTable aliases;
    @XmlElement(name = "Extensions")
    protected ListOfExtensions extensions;
    @XmlElement(name = "NodesToAdd")
    protected NodesToAdd nodesToAdd;
    @XmlElement(name = "ReferencesToAdd")
    protected ReferencesToChange referencesToAdd;
    @XmlElement(name = "NodesToDelete")
    protected NodesToDelete nodesToDelete;
    @XmlElement(name = "ReferencesToDelete")
    protected ReferencesToChange referencesToDelete;
    @XmlAttribute(name = "LastModified")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModified;
    @XmlAttribute(name = "TransactionId", required = true)
    protected String transactionId;
    @XmlAttribute(name = "AcceptAllOrNothing")
    protected Boolean acceptAllOrNothing;

    /**
     * Gets the value of the namespaceUris property.
     * 
     * @return
     *     possible object is
     *     {@link UriTable }
     *     
     */
    public UriTable getNamespaceUris() {
        return namespaceUris;
    }

    /**
     * Sets the value of the namespaceUris property.
     * 
     * @param value
     *     allowed object is
     *     {@link UriTable }
     *     
     */
    public void setNamespaceUris(UriTable value) {
        this.namespaceUris = value;
    }

    /**
     * Gets the value of the serverUris property.
     * 
     * @return
     *     possible object is
     *     {@link UriTable }
     *     
     */
    public UriTable getServerUris() {
        return serverUris;
    }

    /**
     * Sets the value of the serverUris property.
     * 
     * @param value
     *     allowed object is
     *     {@link UriTable }
     *     
     */
    public void setServerUris(UriTable value) {
        this.serverUris = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link AliasTable }
     *     
     */
    public AliasTable getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliasTable }
     *     
     */
    public void setAliases(AliasTable value) {
        this.aliases = value;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfExtensions }
     *     
     */
    public ListOfExtensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfExtensions }
     *     
     */
    public void setExtensions(ListOfExtensions value) {
        this.extensions = value;
    }

    /**
     * Gets the value of the nodesToAdd property.
     * 
     * @return
     *     possible object is
     *     {@link NodesToAdd }
     *     
     */
    public NodesToAdd getNodesToAdd() {
        return nodesToAdd;
    }

    /**
     * Sets the value of the nodesToAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodesToAdd }
     *     
     */
    public void setNodesToAdd(NodesToAdd value) {
        this.nodesToAdd = value;
    }

    /**
     * Gets the value of the referencesToAdd property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesToChange }
     *     
     */
    public ReferencesToChange getReferencesToAdd() {
        return referencesToAdd;
    }

    /**
     * Sets the value of the referencesToAdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesToChange }
     *     
     */
    public void setReferencesToAdd(ReferencesToChange value) {
        this.referencesToAdd = value;
    }

    /**
     * Gets the value of the nodesToDelete property.
     * 
     * @return
     *     possible object is
     *     {@link NodesToDelete }
     *     
     */
    public NodesToDelete getNodesToDelete() {
        return nodesToDelete;
    }

    /**
     * Sets the value of the nodesToDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodesToDelete }
     *     
     */
    public void setNodesToDelete(NodesToDelete value) {
        this.nodesToDelete = value;
    }

    /**
     * Gets the value of the referencesToDelete property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesToChange }
     *     
     */
    public ReferencesToChange getReferencesToDelete() {
        return referencesToDelete;
    }

    /**
     * Sets the value of the referencesToDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesToChange }
     *     
     */
    public void setReferencesToDelete(ReferencesToChange value) {
        this.referencesToDelete = value;
    }

    /**
     * Gets the value of the lastModified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModified() {
        return lastModified;
    }

    /**
     * Sets the value of the lastModified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModified(XMLGregorianCalendar value) {
        this.lastModified = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }

    /**
     * Gets the value of the acceptAllOrNothing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAcceptAllOrNothing() {
        if (acceptAllOrNothing == null) {
            return false;
        } else {
            return acceptAllOrNothing;
        }
    }

    /**
     * Sets the value of the acceptAllOrNothing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAcceptAllOrNothing(Boolean value) {
        this.acceptAllOrNothing = value;
    }

}
